-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "JobCategory" ADD VALUE 'CLEANING';
ALTER TYPE "JobCategory" ADD VALUE 'LAUNDRY';
ALTER TYPE "JobCategory" ADD VALUE 'FUMIGATION';
ALTER TYPE "JobCategory" ADD VALUE 'PAINTING';
ALTER TYPE "JobCategory" ADD VALUE 'TILING';
ALTER TYPE "JobCategory" ADD VALUE 'ROOFING';
ALTER TYPE "JobCategory" ADD VALUE 'MASONRY';
ALTER TYPE "JobCategory" ADD VALUE 'WELDING';
ALTER TYPE "JobCategory" ADD VALUE 'GLASS_ALUMINIUM';
ALTER TYPE "JobCategory" ADD VALUE 'INTERIOR_DESIGN';
ALTER TYPE "JobCategory" ADD VALUE 'CCTV';
ALTER TYPE "JobCategory" ADD VALUE 'FRIDGE';
ALTER TYPE "JobCategory" ADD VALUE 'WASHING_MACHINE';
ALTER TYPE "JobCategory" ADD VALUE 'GENERATOR';
ALTER TYPE "JobCategory" ADD VALUE 'ELECTRONICS';
ALTER TYPE "JobCategory" ADD VALUE 'PHONE_LAPTOP';
ALTER TYPE "JobCategory" ADD VALUE 'SOLAR';
ALTER TYPE "JobCategory" ADD VALUE 'AUTO_ELECTRICIAN';
ALTER TYPE "JobCategory" ADD VALUE 'CAR_AC';
ALTER TYPE "JobCategory" ADD VALUE 'TYRE';
ALTER TYPE "JobCategory" ADD VALUE 'CAR_WASH';
ALTER TYPE "JobCategory" ADD VALUE 'TOWING';
ALTER TYPE "JobCategory" ADD VALUE 'DRIVING_LESSONS';
ALTER TYPE "JobCategory" ADD VALUE 'HAIRDRESSING';
ALTER TYPE "JobCategory" ADD VALUE 'BARBERING';
ALTER TYPE "JobCategory" ADD VALUE 'MAKEUP';
ALTER TYPE "JobCategory" ADD VALUE 'NAILS';
ALTER TYPE "JobCategory" ADD VALUE 'MASSAGE';
ALTER TYPE "JobCategory" ADD VALUE 'FITNESS';
ALTER TYPE "JobCategory" ADD VALUE 'TATTOO';
ALTER TYPE "JobCategory" ADD VALUE 'CATERING';
ALTER TYPE "JobCategory" ADD VALUE 'DJ';
ALTER TYPE "JobCategory" ADD VALUE 'MC';
ALTER TYPE "JobCategory" ADD VALUE 'PHOTOGRAPHY';
ALTER TYPE "JobCategory" ADD VALUE 'VIDEOGRAPHY';
ALTER TYPE "JobCategory" ADD VALUE 'DECORATION';
ALTER TYPE "JobCategory" ADD VALUE 'SOUND';
ALTER TYPE "JobCategory" ADD VALUE 'TENT_CHAIR';
ALTER TYPE "JobCategory" ADD VALUE 'BAND';
ALTER TYPE "JobCategory" ADD VALUE 'TUTORING';
ALTER TYPE "JobCategory" ADD VALUE 'LANGUAGES';
ALTER TYPE "JobCategory" ADD VALUE 'MUSIC_LESSONS';
ALTER TYPE "JobCategory" ADD VALUE 'CHILDMINDING';
ALTER TYPE "JobCategory" ADD VALUE 'SPECIAL_NEEDS';
ALTER TYPE "JobCategory" ADD VALUE 'GRAPHIC_DESIGN';
ALTER TYPE "JobCategory" ADD VALUE 'WEB_DEV';
ALTER TYPE "JobCategory" ADD VALUE 'SOCIAL_MEDIA';
ALTER TYPE "JobCategory" ADD VALUE 'VIDEO_EDITING';
ALTER TYPE "JobCategory" ADD VALUE 'PRINTING';
ALTER TYPE "JobCategory" ADD VALUE 'ACCOUNTING';
ALTER TYPE "JobCategory" ADD VALUE 'LEGAL';
ALTER TYPE "JobCategory" ADD VALUE 'TRANSLATION';
ALTER TYPE "JobCategory" ADD VALUE 'MOVING';
ALTER TYPE "JobCategory" ADD VALUE 'DELIVERY';
ALTER TYPE "JobCategory" ADD VALUE 'TRUCK_HIRE';
